<script setup lang="ts">
import { getAverageColor, toBytes } from 'hazehash';
import images from '~/data/images.json';

interface Credit {
  file: string;
  title: string;
  author: string;
  license: string;
  licenseUrl: string;
  sourceUrl: string;
}

// Hashes come from the build-time manifest generated by the hazehash-nuxt module.
const hashes = images.map((image) => useHazeHash(`/images/${image.file}`));

const kb = (bytes: number) => (bytes / 1024).toFixed(1);
const hex = (c: { r: number; g: number; b: number }) =>
  '#' + [c.r, c.g, c.b].map((v) => v.toString(16).padStart(2, '0')).join('');

const rows = computed(() =>
  images.map((image, i) => {
    const hash = hashes[i].value ?? '';
    const hashBytes = hash ? toBytes(hash).length : 0;
    return {
      ...image,
      src: `/images/${image.file}`,
      hash,
      hashBytes,
      times: hashBytes ? Math.round(image.bytes / hashBytes) : 0,
      color: hash ? getAverageColor(hash) : null,
    };
  }),
);

const totals = computed(() => {
  const original = rows.value.reduce((s, r) => s + r.bytes, 0);
  const hash = rows.value.reduce((s, r) => s + r.hashBytes, 0);
  return { original, hash, times: hash ? Math.round(original / hash) : 0 };
});

const credits: Credit[] = images;
</script>

<template>
  <main class="page">
    <header class="intro">
      <h1>HazeHash</h1>
      <p>
        Each image below is shown next to the placeholder that is rebuilt
        <strong>only from its hash</strong>: a string of at most 28 bytes generated at build time by
        the <code>hazehash-nuxt</code> module. The placeholder is decoded to 32 px and stretched,
        which is what a page shows while the real image is still loading.
      </p>
      <dl class="stats">
        <div>
          <dt>Images</dt>
          <dd>{{ rows.length }}</dd>
        </div>
        <div>
          <dt>Originals (600 px)</dt>
          <dd>{{ kb(totals.original) }} KB</dd>
        </div>
        <div>
          <dt>All hashes</dt>
          <dd>{{ totals.hash }} B</dd>
        </div>
        <div>
          <dt>Hashes are smaller by</dt>
          <dd>{{ totals.times.toLocaleString('en-US') }}×</dd>
        </div>
      </dl>
    </header>

    <div class="scroll">
      <table>
        <thead>
          <tr>
            <th>Original</th>
            <th>Placeholder</th>
            <th>Hash</th>
            <th class="num">Original size</th>
            <th class="num">Hash size</th>
            <th class="num">Smaller by</th>
            <th>Average colour</th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="row in rows" :key="row.file">
            <td>
              <div
                class="frame"
                :class="{ checker: row.hasAlpha }"
                :style="{ aspectRatio: `${row.width} / ${row.height}` }"
              >
                <img
                  :src="row.src"
                  :alt="row.title"
                  :width="row.width"
                  :height="row.height"
                  loading="lazy"
                />
              </div>
            </td>
            <td>
              <div class="frame" :class="{ checker: row.hasAlpha }">
                <!-- Only the hash is passed, so nothing but the placeholder is drawn. -->
                <PlaceholderImage :hash="row.hash" :width="row.width" :height="row.height" />
              </div>
            </td>
            <td class="hash">
              <code>{{ row.hash }}</code>
              <span class="muted"
                >{{ row.hash.length }} characters<template v-if="row.hasAlpha"
                  >, with alpha</template
                ></span
              >
            </td>
            <td class="num">
              {{ kb(row.bytes) }} KB
              <span class="muted">{{ row.width }}×{{ row.height }}</span>
            </td>
            <td class="num">{{ row.hashBytes }} B</td>
            <td class="num">{{ row.times.toLocaleString('en-US') }}×</td>
            <td>
              <span v-if="row.color" class="swatch" :style="{ background: hex(row.color) }" />
              <code v-if="row.color">{{ hex(row.color) }}</code>
            </td>
          </tr>
        </tbody>
      </table>
    </div>

    <section class="credits">
      <h2>Image credits</h2>
      <p class="muted">
        Images are resized to 600 px on the long side. All were found on Wikimedia Commons.
      </p>
      <ul>
        <li v-for="credit in credits" :key="credit.file">
          <a :href="credit.sourceUrl" rel="noopener">{{ credit.title }}</a
          >, {{ credit.author }},
          <a :href="credit.licenseUrl" rel="noopener">{{ credit.license }}</a>
        </li>
      </ul>
    </section>
  </main>
</template>

<style>
:root {
  color-scheme: light dark;
  --bg: #ffffff;
  --fg: #111827;
  --muted: #6b7280;
  --line: #e5e7eb;
  --card: #f3f4f6;
  --accent: #2563eb;
}
@media (prefers-color-scheme: dark) {
  :root {
    --bg: #0b0f17;
    --fg: #e5e7eb;
    --muted: #9ca3af;
    --line: #1f2937;
    --card: #111827;
    --accent: #60a5fa;
  }
}
body {
  margin: 0;
  background: var(--bg);
  color: var(--fg);
  font:
    15px/1.5 system-ui,
    -apple-system,
    'Segoe UI',
    sans-serif;
}
.page {
  max-width: 1100px;
  margin: 0 auto;
  padding: 32px 16px 64px;
}
h1 {
  margin: 0 0 8px;
  font-size: 32px;
}
a {
  color: var(--accent);
}
code {
  font:
    13px ui-monospace,
    SFMono-Regular,
    Menlo,
    Consolas,
    monospace;
}
.muted {
  color: var(--muted);
  font-size: 13px;
}
.intro p {
  max-width: 70ch;
  margin: 0 0 20px;
}
.stats {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
  gap: 12px;
  margin: 0 0 32px;
}
.stats div {
  background: var(--card);
  border-radius: 10px;
  padding: 12px 16px;
}
.stats dt {
  color: var(--muted);
  font-size: 13px;
}
.stats dd {
  margin: 2px 0 0;
  font-size: 22px;
  font-weight: 600;
  font-variant-numeric: tabular-nums;
}
.scroll {
  overflow-x: auto;
}
table {
  width: 100%;
  min-width: 860px;
  border-collapse: collapse;
}
th,
td {
  padding: 12px 10px;
  border-bottom: 1px solid var(--line);
  text-align: left;
  vertical-align: middle;
}
th {
  color: var(--muted);
  font-size: 13px;
  font-weight: 600;
}
.num {
  text-align: right;
  font-variant-numeric: tabular-nums;
}
.num .muted,
.hash .muted {
  display: block;
}
.hash code {
  display: block;
  max-width: 14ch;
  overflow-wrap: anywhere;
}
.frame {
  width: 220px;
  overflow: hidden;
  border-radius: 8px;
}
.frame img {
  display: block;
  width: 100%;
  height: auto;
}
/* Checkerboard behind transparent images, so the alpha channel is visible. */
.checker {
  background-color: #fff;
  background-image:
    linear-gradient(45deg, #cfd4dc 25%, transparent 25%, transparent 75%, #cfd4dc 75%),
    linear-gradient(45deg, #cfd4dc 25%, transparent 25%, transparent 75%, #cfd4dc 75%);
  background-size: 16px 16px;
  background-position:
    0 0,
    8px 8px;
}
.swatch {
  display: inline-block;
  width: 16px;
  height: 16px;
  margin-right: 6px;
  vertical-align: -3px;
  border-radius: 4px;
  border: 1px solid var(--line);
}
.credits {
  margin-top: 48px;
}
.credits h2 {
  font-size: 18px;
}
.credits li {
  margin: 4px 0;
  font-size: 13px;
}
</style>
