import { computed, toValue, type MaybeRefOrGetter } from 'vue';
// @ts-expect-error virtual module generated by the hazehash Nuxt module
import manifest from '#hazehash/manifest';

/** Looks up the build-time hash of an image URL, e.g. `/images/photo.jpg`. */
export function useHazeHash(src: MaybeRefOrGetter<string | undefined | null>) {
  return computed<string | undefined>(() => {
    const url = toValue(src);
    return url ? (manifest as Record<string, string>)[url] : undefined;
  });
}
